default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: johnpaul.bocatija.14@gmail.com
  password: heroku@JP14
  host: localhost
  port: 5432

development:
  <<: *default
  database: cafe_management_postgresql
  
test:
  <<: *default
  database: cafe_management_test

production:
  <<: *default
  database: cafe_management_prod